##################################################
# AUTHOR: FARNAM KHALILI MAYBODI (FKHM)
# COMPANY: UNISI
# DATE: 2021/10/19
##################################################
PROJECT:=$(shell basename "${PWD}")
MODULE:= $(shell echo "${PROJECT}" | cut -c5-32)
export PROJECT
export MODULE
include ../common.mk
