##################################################
# AUTHOR: FARNAM KHALILI MAYBODI (FKHM)
# DATE: 2021/10/19
##################################################
PROJECT:=$(shell basename "${PWD}")
MODULE:= $(shell echo "${PROJECT}")
export PROJECT
export MODULE
include ../common.mk
